####################################################
# LSrouter.py
# Name:
# HUID:
#####################################################

from router import Router
from packet import Packet
import json


class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.neighbors = {} # port -> (neighbor_addr, cost)
        self.ls_db = {self.addr: {"neighbors": {}, "seq": 0}} # origin_addr -> {"neighbors": {addr: cost}, "seq": int}
        self.forwarding_table = {} # dst_addr -> port

    def broadcast_lsa(self, exclude_port=None):
        """Broadcast this router's link-state advertisement to all neighbors."""
        # TODO
        #   tạo LS advertisement chứa thông tin về địa chỉ nguồn, sequence number, neighbors của router
        #   gửi tới tất cả các neighbors trong ls_db ngoại trừ exlude_port nếu có (flooding)
        lsa = {
            "origin": self.addr,
            "seq": self.ls_db[self.addr]["seq"],
            "neighbors": dict(self.ls_db[self.addr]["neighbors"]),}
        content = json.dumps(lsa) # chuyển lsa sang một chuỗi json để gửi đi qua mạng
        packet = Packet(Packet.ROUTING, self.addr, self.addr, content)
        for port in self.links: 
            if port != exclude_port:
                self.send(port, packet) #gửi packet tới tất cả các neighbors nếu có cổng khác exclude_port
    

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            pass
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors
            pass

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        pass

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        pass

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the link state of this router to all neighbors
            pass

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"LSrouter(addr={self.addr})"
