####################################################
# LSrouter.py
# Name:
# HUID:
#####################################################

from router import Router
from packet import Packet
import json
import heapq


class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.neighbors = {} # port -> (neighbor_addr, cost)
        self.ls_db = {self.addr: {"neighbors": {}, "seq": 0}} # origin_addr -> {"neighbors": {addr: cost}, "seq": int}
        self.forwarding_table = {} # dst_addr -> port

    def broadcast_lsa(self, exclude_port=None):
        """Broadcast this router's link-state advertisement to all neighbors."""
        # TODO
        #   tạo LS advertisement chứa thông tin về địa chỉ nguồn, sequence number, neighbors của router
        #   gửi tới tất cả các neighbors trong ls_db ngoại trừ exlude_port nếu có (flooding)
        lsa = {
            "origin": self.addr,
            "seq": self.ls_db[self.addr]["seq"],
            "neighbors": dict(self.ls_db[self.addr]["neighbors"]),}
        content = json.dumps(lsa) # chuyển lsa sang một chuỗi json để gửi đi qua mạng
        packet = Packet(Packet.ROUTING, self.addr, self.addr, content)
        for port in self.links: 
            if port != exclude_port:
                self.send(port, packet) #gửi packet tới tất cả các neighbors nếu có cổng khác exclude_port
    
    def run_dijkstra(self):
        graph = {}
        for origin, data in self.ls_db.items():
            if origin not in graph:
                graph[origin] = {}
            for neighbor, cost in data["neighbors"].items():
                graph[origin][neighbor] = cost
                

        #Thuật toán dijkstra tính đường đi ngắn nhất từ router này đến tất cả các router dựa trên graph được xây dựng từ ls_db
        dist = {self.addr: 0} #
        # first_hop_port lưu cổng đầu tiên trên đường đi từ self đến router đích
        first_hop_port = {self.addr: None}

        heap = [(0, self.addr)]
        visited = set()

        while heap:
            cost, u = heapq.heappop(heap)
            if u in visited:
                continue
            visited.add(u)

            for v, w in graph.get(u, {}).items():
                new_cost = cost + w
                if v not in dist or new_cost < dist[v]:
                    dist[v] = new_cost
                    # nếu u là router hiện tại, cổng đầu tiên để đến v là cổng trực tiếp kết nối đến neighbor v. Nếu u không phải là router hiện tại, cổng đầu tiên để đến v là cổng đầu tiên để đến u.
                    if u == self.addr:
                        # tìm cổng kết nối trực tiếp đến neighbor v bằng cách duyệt neighbors của router hiện tại
                        port = self.port_to_neighbor(v)
                        first_hop_port[v] = port
                    else:
                        first_hop_port[v] = first_hop_port.get(u)
                    heapq.heappush(heap, (new_cost, v))

        self.forwarding_table = {}
        for dst, port in first_hop_port.items():
            if dst != self.addr and port is not None:
                self.forwarding_table[dst] = port

    def port_to_neighbor(self, neighbor_addr):
        """Helper function to find the port that connects to a given neighbor."""
        for port, (addr, cost) in self.neighbors.items():
            if addr == neighbor_addr:
                return port
        return None


    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            dst = packet.dst_addr
            if dst in self.forwarding_table:
                self.send(self.forwarding_table[dst], packet)
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors
            lsa = json.loads(packet.content)
            origin = lsa["origin"]
            seq = lsa["seq"]
            neighbors = lsa["neighbors"]

            if origin not in self.ls_db or self.ls_db[origin]["seq"] < seq:
                # Update LS database
                self.ls_db[origin] = {"neighbors": neighbors, "seq": seq}
                self.run_dijkstra() #cập nhật forwarding table sau khi có sự thay đổi về link state
                for p in self.links:
                    if p != port:
                        self.send(p, packet) #flooding packet tới tất cả các neighbors nếu có cổng khác exclude_port
            else: return            


    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        self.neighbors[port] = (endpoint, cost) #cập nhật neighbors với thông tin neighbor mới
        self.ls_db[self.addr]["neighbors"][endpoint] = cost #cập nhật ls_db với thông tin neighbor mới
        self.ls_db[self.addr]["seq"] += 1 #tăng phiên bản của router trong ls_db
        self.run_dijkstra() #cập nhật forwarding table sau khi có sự thay đổi về liên kết
        self.broadcast_lsa()
                    

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        if port in self.neighbors:
            endpoint, cost = self.neighbors.pop(port) #xóa neighbor khỏi neighbors
            if endpoint in self.ls_db[self.addr]["neighbors"]:
                del self.ls_db[self.addr]["neighbors"][endpoint] #xóa neighbor khỏi ls_db
                self.ls_db[self.addr]["seq"] += 1 #tăng phiên bản của router trong ls_db
                self.run_dijkstra() #cập nhật forwarding table sau khi có sự thay đổi về liên kết
                self.broadcast_lsa() #broadcast LSA mới sau khi có sự thay đổi về liên kết

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the link state of this router to all neighbors
            self.ls_db[self.addr]["seq"] += 1 #tăng phiên bản của router trong ls_db
            self.broadcast_lsa() #broadcast LSA mới sau khi có sự thay đổi về liên
            

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"LSrouter(addr={self.addr})"
